name             'elasticsearch'
maintainer       'Nick Ramirez'
maintainer_email 'nickram44@gmail.com'
license          'all_rights'
description      'Installs/Configures elasticsearch'
long_description 'Installs/Configures elasticsearch'
version          '0.1.0'
